server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: users-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/usuarios/**

            - id: inventario-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/inventario/**
              filters:
                - StripPrefix=0

            - id: mesas-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/mesas/**
              filters:
                - StripPrefix=0

            - id: prophet-service
              uri: http://localhost:8000
              predicates:
                - Path=/api/prophet/**
              filters:
                - StripPrefix=2


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
